name = "malton-automation"
main = "worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
minify = true

[assets]
directory = "dist/public"
binding = "ASSETS"

[vars]
NODE_ENV = "production"
